#### Descripció
Aprèn a gestionar paràmetres amb Python.

In [171]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

### Nivell 1
- **Exercici 1**

Agafa un conjunt de dades de tema esportiu que t'agradi i normalitza els atributs categòrics en dummy. Estandaritza els atributs numèrics amb StandardScaler.

Se importa un dataset con los resultados de los mundiales del League of Legends de 2021. Incluye datos catégoricos (equipos, jugadores campeones usados y resultado) y numéricos (muertes, asistencias, oro ganado, daño, etc).

In [172]:
raw_df = pd.read_csv('lol2021.csv')
raw_df

Team    Player Opponent Position Champion  Kills  Deaths  Assists  \
0    UOL      Boss       GS      Top  Camille      4       5        3   
1     GS     Crazy      UOL      Top     Gwen      3       1        9   
2    UOL  Ahahacik       GS   Jungle  Trundle      2       4        5   
3     GS    Mojito      UOL   Jungle    Talon      5       4       10   
4    UOL    Nomanz       GS      Mid  Leblanc      1       3        4   
..   ...       ...      ...      ...      ...    ...     ...      ...   
215  BYG     Maoan      UOL      Mid     Ryze      4       4        2   
216  UOL  Argonavt      BYG      Adc    Senna      1       3        9   
217  BYG     Doggo      UOL      Adc   Draven     10       2        4   
218  UOL    Santas      BYG  Support   Wukong      0       4        7   
219  BYG      Kino      UOL  Support    Rakan      0       5        9   

     Creep Score  Gold Earned  Champion Damage Share  Kill Participation  \
0            188        11107                   0.17                0.78   
1            217        12201                   0.20                0.52   
2            156         9048                   0.15                0.78   
3            194        11234                   0.23                0.65   
4            216         9245                   0.29                0.56   
..           ...          ...                    ...                 ...   
215          356        15558                   0.23                0.32   
216           58         9554                   0.16                0.71   
217          353        20546                   0.38                0.74   
218          200        10354                   0.11                0.50   
219           41         9304                   0.06                0.47   

     Wards Placed  Wards Destroyed  Ward Interactions  Dragons For  \
0               8                8                 16            0   
1              10                7                 17            4   
2               8               14                 22            0   
3              12                8                 20            4   
4               6                9                 15            0   
..            ...              ...                ...          ...   
215            24                6                 30            4   
216            35               16                 51            1   
217            15                5                 20            4   
218            16                8                 24            1   
219            49               15                 64            4   

     Dragons Against  Barons For  Barons Against Result  
0                  4           0               1      L  
1                  0           1               0      W  
2                  4           0               1      L  
3                  0           1               0      W  
4                  4           0               1      L  
..               ...         ...             ...    ...  
215                1           1               1      W  
216                4           1               1      L  
217                1           1               1      W  
218                4           1               1      L  
219                1           1               1      W  

[220 rows x 20 columns]

Se normaliza los datos de muertes y torretas contruidas

In [173]:
ss = StandardScaler()

Xstd = ss.fit_transform(raw_df[['Kills', 'Wards Placed']].values)
Xstd

array([[ 0.50155703, -0.73062203],
       [ 0.11302694, -0.6030531 ],
       [-0.27550316, -0.73062203],
       [ 0.89008713, -0.47548418],
       [-0.66403326, -0.85819095],
       [ 0.89008713, -0.15656186],
       [-0.66403326, -0.79440649],
       [ 2.44420752, -0.28413079],
       [-0.66403326,  1.31048078],
       [-1.05256335,  1.05534293],
       [-0.66403326, -0.6030531 ],
       [-0.66403326, -0.34791525],
       [-0.66403326, -0.53926864],
       [-1.05256335, -0.53926864],
       [-0.66403326, -0.66683756],
       [ 2.05567742, -0.6030531 ],
       [-0.66403326, -0.73062203],
       [ 0.11302694, -0.41169971],
       [-1.05256335,  1.62940309],
       [-0.66403326,  1.88454094],
       [ 1.27861723, -0.79440649],
       [-0.66403326, -0.41169971],
       [ 0.89008713, -0.41169971],
       [ 0.11302694, -0.41169971],
       [-1.05256335, -0.22034633],
       [-0.27550316, -0.0927774 ],
       [ 0.89008713, -0.22034633],
       [ 0.11302694, -0.34791525],
       [-0.66403326,

In [174]:
print (Xstd.mean())
print (Xstd.std())

5.652044489000796e-17
1.0


In [175]:
x = raw_df[['Kills', 'Creep Score', 'Gold Earned']]
mms = MinMaxScaler()
Xn = mms.fit_transform(x)

In [176]:
Xn.min(axis=0)

array([0., 0., 0.])

In [177]:
Xn.max(axis=0)

array([1., 1., 1.])

Se muestra un nuevo DF con los datos categórigos tratados con libreria Dummie, generando nuevas columnas para los equipos y los resultados del torneo.

In [178]:
dummies = pd.get_dummies(raw_df, columns=["Team", "Result"])

print("Original DataFrame:")
raw_df

Original DataFrame:


Team    Player Opponent Position Champion  Kills  Deaths  Assists  \
0    UOL      Boss       GS      Top  Camille      4       5        3   
1     GS     Crazy      UOL      Top     Gwen      3       1        9   
2    UOL  Ahahacik       GS   Jungle  Trundle      2       4        5   
3     GS    Mojito      UOL   Jungle    Talon      5       4       10   
4    UOL    Nomanz       GS      Mid  Leblanc      1       3        4   
..   ...       ...      ...      ...      ...    ...     ...      ...   
215  BYG     Maoan      UOL      Mid     Ryze      4       4        2   
216  UOL  Argonavt      BYG      Adc    Senna      1       3        9   
217  BYG     Doggo      UOL      Adc   Draven     10       2        4   
218  UOL    Santas      BYG  Support   Wukong      0       4        7   
219  BYG      Kino      UOL  Support    Rakan      0       5        9   

     Creep Score  Gold Earned  Champion Damage Share  Kill Participation  \
0            188        11107                   0.17                0.78   
1            217        12201                   0.20                0.52   
2            156         9048                   0.15                0.78   
3            194        11234                   0.23                0.65   
4            216         9245                   0.29                0.56   
..           ...          ...                    ...                 ...   
215          356        15558                   0.23                0.32   
216           58         9554                   0.16                0.71   
217          353        20546                   0.38                0.74   
218          200        10354                   0.11                0.50   
219           41         9304                   0.06                0.47   

     Wards Placed  Wards Destroyed  Ward Interactions  Dragons For  \
0               8                8                 16            0   
1              10                7                 17            4   
2               8               14                 22            0   
3              12                8                 20            4   
4               6                9                 15            0   
..            ...              ...                ...          ...   
215            24                6                 30            4   
216            35               16                 51            1   
217            15                5                 20            4   
218            16                8                 24            1   
219            49               15                 64            4   

     Dragons Against  Barons For  Barons Against Result  
0                  4           0               1      L  
1                  0           1               0      W  
2                  4           0               1      L  
3                  0           1               0      W  
4                  4           0               1      L  
..               ...         ...             ...    ...  
215                1           1               1      W  
216                4           1               1      L  
217                1           1               1      W  
218                4           1               1      L  
219                1           1               1      W  

[220 rows x 20 columns]

In [179]:
print("DataFrame with Dummies:")
dummies

DataFrame with Dummies:


Player Opponent Position Champion  Kills  Deaths  Assists  Creep Score  \
0        Boss       GS      Top  Camille      4       5        3          188   
1       Crazy      UOL      Top     Gwen      3       1        9          217   
2    Ahahacik       GS   Jungle  Trundle      2       4        5          156   
3      Mojito      UOL   Jungle    Talon      5       4       10          194   
4      Nomanz       GS      Mid  Leblanc      1       3        4          216   
..        ...      ...      ...      ...    ...     ...      ...          ...   
215     Maoan      UOL      Mid     Ryze      4       4        2          356   
216  Argonavt      BYG      Adc    Senna      1       3        9           58   
217     Doggo      UOL      Adc   Draven     10       2        4          353   
218    Santas      BYG  Support   Wukong      0       4        7          200   
219      Kino      UOL  Support    Rakan      0       5        9           41   

     Gold Earned  Champion Damage Share  ...  Team_DFM  Team_GS  Team_HLE  \
0          11107                   0.17  ...         0        0         0   
1          12201                   0.20  ...         0        1         0   
2           9048                   0.15  ...         0        0         0   
3          11234                   0.23  ...         0        1         0   
4           9245                   0.29  ...         0        0         0   
..           ...                    ...  ...       ...      ...       ...   
215        15558                   0.23  ...         0        0         0   
216         9554                   0.16  ...         0        0         0   
217        20546                   0.38  ...         0        0         0   
218        10354                   0.11  ...         0        0         0   
219         9304                   0.06  ...         0        0         0   

     Team_INF  Team_LNG  Team_PCE  Team_RED  Team_UOL  Result_L  Result_W  
0           0         0         0         0         1         1         0  
1           0         0         0         0         0         0         1  
2           0         0         0         0         1         1         0  
3           0         0         0         0         0         0         1  
4           0         0         0         0         1         1         0  
..        ...       ...       ...       ...       ...       ...       ...  
215         0         0         0         0         0         0         1  
216         0         0         0         0         1         1         0  
217         0         0         0         0         0         0         1  
218         0         0         0         0         1         1         0  
219         0         0         0         0         0         0         1  

[220 rows x 30 columns]

### Nivell 2
- **Exercici 2**

Continua amb el conjunt de dades de tema esportiu que t'agradi i aplica l'anàlisi de components principals.

### Nivell 3
- **Exercici 3**

Continua amb el conjunt de dades de tema esportiu que t'agradi i normalitza les dades tenint en compte els outliers.